version: '3.5'
services:
  MovieService:
   image: ${DOCKER_REGISTRY-}usersmicroservice:v1
   build:
    context: ./MovieService
    dockerfile: Dockerfile
   environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.1.2,1433;Initial Catalog=MovieDB;User Id=******;Password=******
   ports:
    - "4202:80"